ACONITE STUDIOS - DONT STEAL MY SHIT ( DSMS ) - V1.0.0
29 / 06 / 24

COPYTIGHT (C) 2024 ACONITE STUDIOS

THIS MAY CHANGE AT ANY TIME. IF IT CHANGES, UPDATE YOUR PROJECT TO FOLLOW ANY NEW GUIDELINES

TERMS AND CONDITIONS

- INSPIRATION 
  YOU ARE ALLOWED TO USE THE RESOURSES PROVIDED BY ANY PROJECT UNDER THIS LICENCE FOR INSPIRATION AND TO LEARN
  YOU ARE PROHIBITED FROM STEALING CODE, TEXTURES, AND OR MODELS

- RECREATION
  YOU ARE ALLOWED TO SIMILAR-ISH IDEAS ( WITH CREDIT )
  YOU ARE PROHIBITED FROM STEALING IDEAS

- PORTING
  YOU ARE ALLOWED TO PORT ( WITH PERMISSION )
  YOU ARE PROHIBITED TO PORT TO FORGE, OR PORT WITH NO PERMISSION
  YOU MUST UPLOAD YOUR PORT TO GITHUB AND PERMISSION MUST BE VISIBLE ON THE REPOSITORY
